# Generated by Django 4.2.1 on 2023-05-06 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('C', 'Son Kullanıcı'), ('P', 'İş Ortağı')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relations.company')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now=True)),
                ('exp_end_date', models.DateField()),
                ('tender_date', models.DateField()),
                ('info', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('count', models.IntegerField()),
                ('budget', models.FloatField()),
                ('poc_request', models.CharField(choices=[('Y', 'Evet'), ('N', 'Hayır')], max_length=1)),
                ('probability', models.CharField(max_length=3)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='relations.company')),
                ('client_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_contact', to='relations.people')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='relations.company')),
                ('partner_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_contact', to='relations.people')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relations.product')),
            ],
        ),
    ]
