# Generated by Django 4.2.1 on 2023-05-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='role',
            field=models.CharField(choices=[('client', 'Son Kullanıcı'), ('partner', 'İş Ortağı')], max_length=7),
        ),
    ]
